services:

  server:
    build:
      context: ../
      dockerfile: build/docker/service/Dockerfile
    container_name: server
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - postgres

  postgres:
    container_name: hospital_pg
    build:
      context: ../build/docker/db/postgres
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - pgs_hospital_volume:/var/lib/postgresql/data
    ports:
      - "5612:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

volumes:
  pgs_hospital_volume: